project_name: mdathome
dist: build

before:
  hooks:
    - go mod download

release:
  prerelease: auto
  mode: replace

builds:
  - binary: mdathome
    main: main.go
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    flags:
      - -trimpath
    ldflags:
      - "{{.Env.LDFLAGS}}"
    hooks:
      post:
        - /bin/sh -c "upx -q '{{.Path}}' || true"
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
      - s390x
      - ppc64le
    goarm:
      - 5
      - 6
      - 7

archives:
  - format: binary

checksum:
  algorithm: sha512
