{
 "title": "Flare's MD@H Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "scale", "query": "15s,30s,1m,5m,10m" },
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Average Process Times [$scale]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.99, rate(client_request_process_seconds_bucket{job=\"$job\"}[$scale])))",
     "legendFormat": "99th Process"
    },
    {
     "expr": "avg(histogram_quantile(0.97, rate(client_request_process_seconds_bucket{job=\"$job\"}[$scale])))",
     "legendFormat": "97th Process"
    },
    {
     "expr": "avg(histogram_quantile(0.95, rate(client_request_process_seconds_bucket{job=\"$job\"}[$scale])))",
     "legendFormat": "95th Process"
    },
    {
     "expr": "avg(histogram_quantile(0.90, rate(client_request_process_seconds_bucket{job=\"$job\"}[$scale])))",
     "legendFormat": "90th Process"
    }
   ]
  },
  {
   "title": "Average Requests Times [$scale]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.99, rate(client_request_duration_seconds_bucket{job=\"$job\"}[$scale])))",
     "legendFormat": "99th Completed"
    },
    {
     "expr": "avg(histogram_quantile(0.97, rate(client_request_duration_seconds_bucket{job=\"$job\"}[$scale])))",
     "legendFormat": "97th Completed"
    },
    {
     "expr": "avg(histogram_quantile(0.95, rate(client_request_duration_seconds_bucket{job=\"$job\"}[$scale])))",
     "legendFormat": "95th Completed"
    },
    {
     "expr": "avg(histogram_quantile(0.90, rate(client_request_duration_seconds_bucket{job=\"$job\"}[$scale])))",
     "legendFormat": "90th Completed"
    }
   ]
  },
  {
   "title": "Requests Rate [$scale]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(client_requests_total{job=\"$job\"}[$scale]))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(rate(client_hits_total{job=\"$job\"}[$scale]))",
     "legendFormat": "Hits"
    },
    {
     "expr": "sum(rate(client_missed_total{job=\"$job\"}[$scale]))",
     "legendFormat": "Misses"
    },
    {
     "expr": "sum(rate(client_failed_total{job=\"$job\"}[$scale]))",
     "legendFormat": "Failures"
    },
    {
     "expr": "sum(rate(client_corrupted_total[$scale]))",
     "legendFormat": "Checksums"
    }
   ]
  },
  {
   "title": "Network Rate [$scale]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(client_downloaded_bytes_total{job=\"$job\"}[$scale]))",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "sum(rate(client_served_bytes_total{job=\"$job\"}[$scale]))",
     "legendFormat": "Served"
    }
   ]
  },
  {
   "title": "Network in Time Period",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(client_downloaded_bytes_total{job=\"$job\"}[$__range]))",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "sum(increase(client_served_bytes_total{job=\"$job\"}[$__range]))",
     "legendFormat": "Served"
    }
   ]
  },
  {
   "title": "Cache Hit Rate [$scale]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(client_hits_total{job=\"$job\"}[$scale])) / sum(rate(client_requests_total{job=\"$job\"}[$scale]))",
     "legendFormat": "Hit Rate"
    }
   ]
  },
  {
   "title": "Diskcache Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "client_cache_size_bytes{job=\"$job\"} > 0",
     "legendFormat": "Size"
    },
    {
     "expr": "client_cache_limit_bytes{job=\"$job\"} > 0",
     "legendFormat": "Limit"
    },
    {
     "expr": "(client_cache_limit_bytes{job=\"$job\"} > 0) - (client_cache_size_bytes{job=\"$job\"} > 0)",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\"}",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"$job\"}",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "avg_over_time(go_memstats_alloc_bytes{job=\"$job\"}[1m])",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\"}",
     "legendFormat": "Goroutines"
    },
    {
     "expr": "process_num_threads{job=\"$job\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Total Requests By Country [5m]",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (country) (increase(client_requests_total{job=\"$job\",country!=\"\"}[5m]))",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Request Times By Country [5m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(client_request_duration_seconds_bucket{job=\"$job\"}[5m]))",
     "legendFormat": "95th - {{country}}"
    }
   ]
  },
  {
   "title": "Requests By IP [5m]",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(rate({job=\"$job\"}[5m] | json | event = \"received\")) by (remote_addr))",
     "legendFormat": "{{ remote_addr }}"
    }
   ]
  },
  {
   "title": "Requests Rate By Country [1m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(client_requests_total{job=\"$job\", country!=\"\"}[1m])",
     "legendFormat": "Requests  - {{country}}"
    }
   ]
  },
  {
   "title": "Top Shards [5m]",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(rate({job=\"$job\"}[5m] | json | event = \"received\" | line_format \"{{.url_path}}\" | regexp \"/(?:[^/]+)/(?:[^/]+)/(?P<chapter_hash>[^/]*)\")) by (chapter_hash))",
     "legendFormat": "{{ chapter_hash }}"
    }
   ]
  },
  {
   "title": "Non-Received Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "{job=\"$job\"} | json | event != \"received\""
    }
   ]
  }
 ]
}